export const GET_QA_LIST = 'GET_QA_LIST'
export const GET_QA_LIST_SUCCESS = 'GET_QA_LIST_SUCCESS'
export const GET_QA_LIST_FAILURE = 'GET_QA_LIST_FAILURE'

export const GET_QA_CATEGORY_LIST = 'GET_QA_CATEGORY_LIST'
export const GET_QA_CATEGORY_LIST_SUCCESS = 'GET_QA_CATEGORY_LIST_SUCCESS'
export const GET_QA_CATEGORY_LIST_FAILURE = 'GET_QA_CATEGORY_LIST_FAILURE'

export const NEW_QA_CATEGORY = 'NEW_QA_CATEGORY'
export const NEW_QA_CATEGORY_SUCCESS = 'NEW_QA_CATEGORY_SUCCESS'
export const NEW_QA_CATEGORY_FAILURE = 'NEW_QA_CATEGORY_FAILURE'

export const NEW_QA_KIND = 'NEW_QA_KIND'
export const NEW_QA_KIND_SUCCESS = 'NEW_QA_KIND_SUCCESS'
export const NEW_QA_KIND_FAILURE = 'NEW_QA_KIND_FAILURE'
